name: friend tech
networks:
  - id: 8453
    start_block: 7000000
    contracts:
      - name: FriendtechSharesV1
        address:
          - 0xCF205808Ed36593aa40a44F10c7f7C2F67d4A4d4
        handler: src/EventHandlers.ts
        events:
          - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
            requiredEntities:
              - name: EventsSummary
          - event: Trade(address trader, address subject, bool isBuy, uint256 shareAmount, uint256 ethAmount, uint256 protocolEthAmount, uint256 subjectEthAmount, uint256 supply)
            requiredEntities:
              - name: EventsSummary
              - name: Trader
